import type {
  EvaluationRequest,
  PipelineEvent,
  PluginCapabilities,
  PluginFinding,
  PluginRunRecord,
} from "@openleash/shared";
import { codeScannerManifest as manifest } from "./manifest.js";
import { pluginRun } from "./openleash-plugin-runtime.js";

export { manifest };

const MAX_CODE_CHARS = 30_000;

export type CodeScannerVulnerability = {
  title: string;
  severity: "low" | "medium" | "high" | "critical";
  cwe?: string;
  evidence?: string;
  remediation: string;
};

export type CodeScannerAssessment = {
  risky: boolean;
  riskScore: number;
  severity: "none" | "low" | "medium" | "high" | "critical";
  summary: string;
  vulnerabilities: CodeScannerVulnerability[];
};

export const CODE_SCANNER_SYSTEM_PROMPT = [
  "You are OpenLeash code-scanner, a strict application-security reviewer for code generated by AI coding agents.",
  "Find concrete, exploitable security vulnerabilities in the supplied generated code or patch.",
  "Check injection, broken authentication or authorization, secret exposure, unsafe deserialization, path traversal, SSRF, XSS, CSRF, SQL injection, command execution, insecure cryptography, race conditions, supply-chain risk, unsafe file permissions, and dangerous defaults.",
  "Do not report style, maintainability, missing tests, hypothetical concerns without evidence, or vulnerabilities outside the supplied code.",
  "Set risky=true only for a concrete vulnerability. Use riskScore 0-100 and severity none, low, medium, high, or critical.",
  "Evidence must be a short excerpt from the supplied code. Remediation must be specific and actionable.",
  "Return only JSON matching the provided schema.",
].join(" ");

export const CODE_SCANNER_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["risky", "riskScore", "severity", "summary", "vulnerabilities"],
  properties: {
    risky: { type: "boolean" },
    riskScore: { type: "number", minimum: 0, maximum: 100 },
    severity: { enum: ["none", "low", "medium", "high", "critical"] },
    summary: { type: "string" },
    vulnerabilities: {
      type: "array",
      maxItems: 8,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["title", "severity", "remediation"],
        properties: {
          title: { type: "string" },
          severity: { enum: ["low", "medium", "high", "critical"] },
          cwe: { type: "string" },
          evidence: { type: "string" },
          remediation: { type: "string" },
        },
      },
    },
  },
};

export async function runCodeScanner(
  request: EvaluationRequest,
  event: PipelineEvent,
  capabilities: PluginCapabilities,
  config: Record<string, unknown> = {},
): Promise<PluginRunRecord> {
  const startedAt = Date.now();
  const candidate = generatedCodeCandidate(
    request,
    clamp(Number(config.minimumCodeCharacters ?? 80), 40, 4000),
  );
  if (!candidate)
    return pluginRun({
      pluginId: manifest.id,
      event,
      status: "skipped",
      summary: "No generated code was present in this coding-agent event.",
      startedAt,
      metadata: { agentKind: request.agent.kind, reason: "no-code" },
    });

  const evaluation = await capabilities.llm.evaluateJson<CodeScannerAssessment>(
    {
      purpose: "code-scanner",
      system: CODE_SCANNER_SYSTEM_PROMPT,
      prompt: JSON.stringify({
        task: "Evaluate this AI-generated code for concrete security vulnerabilities.",
        agentKind: request.agent.kind,
        agentName: request.agent.displayName,
        event,
        source: candidate.source,
        projectPath: request.event.projectPath,
        languageHint: candidate.languageHint,
        code: candidate.code,
      }),
      schema: CODE_SCANNER_SCHEMA,
      temperature: 0,
      maxOutputTokens: 1400,
    },
  );
  if (!evaluation) {
    await capabilities.log.emit({
      level: "warn",
      category: "plugin",
      code: "code-scanner.evaluation-unavailable",
      message:
        "Code-scanner could not evaluate generated code because no evaluator result was available.",
      data: { agentKind: request.agent.kind, source: candidate.source },
    });
    return pluginRun({
      pluginId: manifest.id,
      event,
      status: "failed",
      summary: "Generated-code security evaluation was unavailable.",
      startedAt,
    });
  }

  const assessment = normalizeAssessment(evaluation.json);
  const risky =
    assessment.risky &&
    assessment.riskScore >=
      clamp(Number(config.notificationRiskThreshold ?? 70), 0, 100) &&
    assessment.vulnerabilities.length > 0;
  const findings: PluginFinding[] = assessment.vulnerabilities.map((item) => ({
    title: item.title,
    severity: item.severity,
    summary: item.remediation,
    evidence: item.evidence ? [item.evidence] : undefined,
  }));
  await capabilities.log.emit({
    level: risky ? "security" : "info",
    category: risky ? "security" : "plugin",
    code: risky ? "code-scanner.risky-code" : "code-scanner.code-reviewed",
    message: risky
      ? "Code-scanner found vulnerabilities in AI-generated code."
      : "Code-scanner reviewed AI-generated code without a notification-level finding.",
    data: {
      agentKind: request.agent.kind,
      source: candidate.source,
      riskScore: assessment.riskScore,
      severity: assessment.severity,
      summary: assessment.summary,
      vulnerabilities: assessment.vulnerabilities,
      model: evaluation.model,
      provider: evaluation.provider,
    },
  });
  if (risky) {
    const primary = assessment.vulnerabilities[0];
    await Promise.all([
      capabilities.signals.emit({
        kind: "security.finding",
        severity:
          assessment.severity === "none" ? "medium" : assessment.severity,
        title: "Risky AI-generated code",
        summary: assessment.summary,
        decision: "observed",
        status: "needs_review",
        target: { type: "generated_code", name: request.agent.displayName },
        evidence: assessment.vulnerabilities,
        details: {
          riskScore: assessment.riskScore,
          source: candidate.source,
          agentKind: request.agent.kind,
        },
        correlationKeys: [
          `agent:${request.agent.kind}`,
          `session:${request.event.sessionId}`,
          "code-scanner",
        ],
      }),
      capabilities.notification.send({
        level: assessment.severity === "critical" ? "critical" : "warning",
        title: "Risky code generated",
        summary: `${request.agent.displayName}: ${primary?.title ?? assessment.summary}. ${primary?.remediation ?? "Review the generated code before using it."}`,
        dedupeKey: `code-scanner:${request.agent.kind}:${request.event.sessionId}:${primary?.title ?? assessment.riskScore}`,
        scope: {
          agentKind: request.agent.kind,
          sessionId: request.event.sessionId,
          projectPath: request.event.projectPath,
        },
        minIntervalSeconds: 300,
      }),
    ]);
  }
  return pluginRun({
    pluginId: manifest.id,
    event,
    status: "passed",
    summary: risky
      ? `Risky generated code detected (${assessment.riskScore}/100). User notified.`
      : `Generated code reviewed (${assessment.riskScore}/100).`,
    startedAt,
    findings,
    metadata: {
      agentKind: request.agent.kind,
      source: candidate.source,
      riskScore: assessment.riskScore,
      severity: assessment.severity,
      notificationSent: risky,
      evaluatedBy: `${evaluation.provider}:${evaluation.model}`,
    },
  });
}

export function generatedCodeCandidate(
  request: EvaluationRequest,
  minimumCharacters = 80,
) {
  const tool = request.event.tool;
  if (
    tool &&
    /(?:write|edit|patch|notebook|create|replace|insert)/i.test(tool.name)
  ) {
    const code = codeFromToolInput(tool.input);
    if (looksLikeCode(code, minimumCharacters))
      return {
        code: truncate(code, MAX_CODE_CHARS),
        source: `tool:${tool.name}`,
        languageHint: languageHint(code),
      };
  }
  const assistant =
    [...(request.event.transcript ?? [])]
      .reverse()
      .find((turn) => turn.role === "assistant")?.content ?? "";
  const fenced = [...assistant.matchAll(/```([^\n`]*)\n([\s\S]*?)```/g)]
    .map((match) => match[2])
    .join("\n\n");
  const code = fenced || assistant;
  if (!looksLikeCode(code, minimumCharacters)) return undefined;
  return {
    code: truncate(code, MAX_CODE_CHARS),
    source: fenced ? "assistant-code-fence" : "assistant-response",
    languageHint: languageHint(fenced ? assistant : code),
  };
}

function codeFromToolInput(input: unknown): string {
  if (typeof input === "string") return input;
  if (!input || typeof input !== "object") return "";
  const record = input as Record<string, unknown>;
  return [
    "content",
    "code",
    "patch",
    "diff",
    "new_string",
    "newText",
    "text",
    "command",
  ]
    .map((key) => record[key])
    .filter((value): value is string => typeof value === "string")
    .join("\n");
}

function looksLikeCode(value: string, minimumCharacters: number) {
  if (value.trim().length < minimumCharacters) return false;
  const markers = [
    /[{};]\s*(?:\n|$)/,
    /\b(?:function|class|const|let|var|def|import|from|SELECT|INSERT|UPDATE|CREATE)\b/,
    /(?:=>|\bif\s*\(|\bfor\s*\(|\breturn\b)/,
    /^\s*(?:diff --git|@@|[+-]{3}\s)/m,
    /<\/?[a-z][^>]*>/i,
  ];
  return markers.filter((pattern) => pattern.test(value)).length >= 2;
}

function normalizeAssessment(
  value: CodeScannerAssessment,
): CodeScannerAssessment {
  const vulnerabilities = Array.isArray(value?.vulnerabilities)
    ? value.vulnerabilities.slice(0, 8).flatMap((item) => {
        const title = truncate(String(item?.title ?? "").trim(), 160);
        const remediation = truncate(
          String(item?.remediation ?? "").trim(),
          400,
        );
        if (
          !title ||
          !remediation ||
          !["low", "medium", "high", "critical"].includes(item.severity)
        )
          return [];
        return [
          {
            title,
            remediation,
            severity: item.severity,
            cwe: item.cwe ? truncate(String(item.cwe), 40) : undefined,
            evidence: item.evidence
              ? truncate(String(item.evidence), 500)
              : undefined,
          },
        ];
      })
    : [];
  const riskScore = clamp(Number(value?.riskScore ?? 0), 0, 100);
  const severity = ["none", "low", "medium", "high", "critical"].includes(
    value?.severity,
  )
    ? value.severity
    : "none";
  return {
    risky: Boolean(value?.risky && vulnerabilities.length),
    riskScore,
    severity,
    summary: truncate(String(value?.summary ?? "Code review completed."), 400),
    vulnerabilities,
  };
}

function languageHint(value: string) {
  return value.match(/```([a-zA-Z0-9+#.-]+)/)?.[1] ?? "unknown";
}
function truncate(value: string, max: number) {
  return value.length <= max ? value : `${value.slice(0, max - 3)}...`;
}
function clamp(value: number, min: number, max: number) {
  return Number.isFinite(value)
    ? Math.max(min, Math.min(max, Math.round(value)))
    : min;
}
